============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/warwolf/tareas/FTYAC_tarea1
collected 2 items

test_Calculator.py .F                                                    [100%]

=================================== FAILURES ===================================
________________________________ test_add_step2 ________________________________

    def test_add_step2():
>       assert add("1,2,3") == 6
E       AssertionError: assert 3 == 6
E        +  where 3 = add('1,2,3')

test_Calculator.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_Calculator.py::test_add_step2 - AssertionError: assert 3 == 6
========================= 1 failed, 1 passed in 0.02s ==========================
